# Generated by Django 4.0.7 on 2022-12-01 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
