# Generated by Django 4.0.7 on 2022-12-01 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_review_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='article',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='articles.article'),
            preserve_default=False,
        ),
    ]
