# Generated by Django 4.0.7 on 2022-12-11 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_review_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='body',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='title',
            new_name='profile',
        ),
    ]
